version: '3'

networks:
  my_cool_network:
    name: my_cool_network

services:
  flask_app:
    container_name: flask-web
    restart: always
    build: ./flask-web
    networks:
      - my_cool_network
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app
